### ISSUE TITLE
ESXI 6.7?

### ISSUE THREAD

**Issue by olegfusion** [aleks-spv/for-zabbix#1]
Hello!

Was it tested on esxi 6.7? My log
2117206:20190125:213447.463 Starting Zabbix Agent [supermicro]. Zabbix 3.2.7 (revision 70298).
2117206:20190125:213447.463 **** Enabled features ****
2117206:20190125:213447.464 IPv6 support:           NO
2117206:20190125:213447.464 TLS support:            NO
2117206:20190125:213447.464 **************************
2117206:20190125:213447.464 using configuration file: /etc/zabbix_agentd.conf
2117206:20190125:213447.464 listener failed: bind() for [[-]:10050] failed: [1] Operation not permitted

I have a similar situation: need to monitor LSI megaraid state using megacli (your zabbix plugin).

So, I have here esxi 6.7 & zabbix 4.0.
1. Can't run zabbix agent from vib packet
2. Can't import zabbix config file (Invalid trigger expression. The "Teamplate LSI raid status on exsi" network node does not exist or you do not have access rights to this network node.)

Thanks for help

**Comment by aleks-spv** [comment]
Hello! At 6.7 not tested. Most likely it will not work, since it already uses its own development of the operating system vmware - Project Photon OS.

**Comment by renatorocco** [comment]
Hello.
i'm trying to use the vmware 6.7 plugin
but it looks like the plugin can't start.
